package com.tiki.advancedlootableweapons.inventory.ForgeWeapon;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.annotation.Nullable;

import com.google.common.collect.HashBasedTable;
import com.google.common.collect.Table;
import com.google.common.collect.Table.Cell;
import com.tiki.advancedlootableweapons.handlers.ConfigHandler;
import com.tiki.advancedlootableweapons.init.ItemInit;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class ForgeWeaponRecipes {
	
	private final List<ItemStack> toolHeadJeiMap = new ArrayList<ItemStack>(13);
	private final Table<List<Item>, List<Item>, Item> armorRecipes = HashBasedTable.<List<Item>, List<Item>, Item>create();
	private final Table<Item, Item, HashMap<String, Item>> recipes = HashBasedTable.<Item, Item, HashMap<String, Item>>create();
	private final Table<ItemStack, ItemStack, List<ItemStack>> jeiRecipes = HashBasedTable.<ItemStack, ItemStack, List<ItemStack>>create();
	private final Map<Item, Integer> expValues = new HashMap<Item, Integer>();
	public static final ForgeWeaponRecipes INSTANCE = new ForgeWeaponRecipes();
	
	public ForgeWeaponRecipes() {
		registerNewRecipe(ItemInit.DAGGER_HOT_TOOL_HEAD_2, ItemInit.HOT_TOOL_ROD_2, "dagger", ConfigHandler.GLOBAL_DAGGER_CRAFTING_EXP,
				new Item[] {ItemInit.DAGGER_IRON, ItemInit.DAGGER_KOBOLD, ItemInit.DAGGER_COPPER, ItemInit.DAGGER_SILVER, ItemInit.DAGGER_BRONZE, ItemInit.DAGGER_PLATINUM,
				ItemInit.DAGGER_STEEL, ItemInit.DAGGER_SHADOW_PLATINUM, ItemInit.DAGGER_FROST_STEEL, ItemInit.DAGGER_OBSIDIAN, ItemInit.DAGGER_CRYSTALLITE, ItemInit.DAGGER_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.KABUTOWARI_HOT_TOOL_HEAD_5, ItemInit.HOT_TOOL_ROD_2, "kabutowari", ConfigHandler.GLOBAL_KABUTOWARI_CRAFTING_EXP,
				new Item[] {ItemInit.KABUTOWARI_IRON, ItemInit.KABUTOWARI_KOBOLD, ItemInit.KABUTOWARI_COPPER, ItemInit.KABUTOWARI_SILVER, ItemInit.KABUTOWARI_BRONZE, ItemInit.KABUTOWARI_PLATINUM,
				ItemInit.KABUTOWARI_STEEL, ItemInit.KABUTOWARI_SHADOW_PLATINUM, ItemInit.KABUTOWARI_FROST_STEEL, ItemInit.KABUTOWARI_OBSIDIAN, ItemInit.KABUTOWARI_CRYSTALLITE, ItemInit.KABUTOWARI_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.RAPIER_HOT_TOOL_HEAD_4, ItemInit.HOT_TOOL_ROD_2, "rapier", ConfigHandler.GLOBAL_RAPIER_CRAFTING_EXP,
				new Item[] {ItemInit.RAPIER_IRON, ItemInit.RAPIER_KOBOLD, ItemInit.RAPIER_COPPER, ItemInit.RAPIER_SILVER, ItemInit.RAPIER_BRONZE, ItemInit.RAPIER_PLATINUM,
				ItemInit.RAPIER_STEEL, ItemInit.RAPIER_SHADOW_PLATINUM, ItemInit.RAPIER_FROST_STEEL, ItemInit.RAPIER_OBSIDIAN, ItemInit.RAPIER_CRYSTALLITE, ItemInit.RAPIER_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.TALWAR_HOT_TOOL_HEAD_3, ItemInit.HOT_TOOL_ROD_2, "talwar", ConfigHandler.GLOBAL_TALWAR_CRAFTING_EXP,
				new Item[] {ItemInit.TALWAR_IRON, ItemInit.TALWAR_KOBOLD, ItemInit.TALWAR_COPPER, ItemInit.TALWAR_SILVER, ItemInit.TALWAR_BRONZE, ItemInit.TALWAR_PLATINUM,
				ItemInit.TALWAR_STEEL, ItemInit.TALWAR_SHADOW_PLATINUM, ItemInit.TALWAR_FROST_STEEL, ItemInit.TALWAR_OBSIDIAN, ItemInit.TALWAR_CRYSTALLITE, ItemInit.TALWAR_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.CLEAVER_HOT_TOOL_HEAD, ItemInit.HOT_TOOL_ROD_2, "cleaver", ConfigHandler.GLOBAL_CLEAVER_CRAFTING_EXP,
				new Item[] {ItemInit.CLEAVER_IRON, ItemInit.CLEAVER_KOBOLD, ItemInit.CLEAVER_COPPER, ItemInit.CLEAVER_SILVER, ItemInit.CLEAVER_BRONZE, ItemInit.CLEAVER_PLATINUM,
				ItemInit.CLEAVER_STEEL, ItemInit.CLEAVER_SHADOW_PLATINUM, ItemInit.CLEAVER_FROST_STEEL, ItemInit.CLEAVER_OBSIDIAN, ItemInit.CLEAVER_CRYSTALLITE, ItemInit.CLEAVER_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.MACE_HOT_TOOL_HEAD_3, ItemInit.HOT_TOOL_ROD_2, "mace", ConfigHandler.GLOBAL_MACE_CRAFTING_EXP,
				new Item[] {ItemInit.MACE_IRON, ItemInit.MACE_KOBOLD, ItemInit.MACE_COPPER, ItemInit.MACE_SILVER, ItemInit.MACE_BRONZE, ItemInit.MACE_PLATINUM,
				ItemInit.MACE_STEEL, ItemInit.MACE_SHADOW_PLATINUM, ItemInit.MACE_FROST_STEEL, ItemInit.MACE_OBSIDIAN, ItemInit.MACE_CRYSTALLITE, ItemInit.MACE_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.MACE_HOT_TOOL_HEAD_2, ItemInit.HOT_TOOL_ROD_2, "mace", ConfigHandler.GLOBAL_MACE_CRAFTING_EXP,
				new Item[] {ItemInit.MACE_IRON, ItemInit.MACE_KOBOLD, ItemInit.MACE_COPPER, ItemInit.MACE_SILVER, ItemInit.MACE_BRONZE, ItemInit.MACE_PLATINUM,
				ItemInit.MACE_STEEL, ItemInit.MACE_SHADOW_PLATINUM, ItemInit.MACE_FROST_STEEL, ItemInit.MACE_OBSIDIAN, ItemInit.MACE_CRYSTALLITE, ItemInit.MACE_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.STAFF_HOT_TOOL_HEAD_2, ItemInit.LONG_TOOL_ROD, "staff", ConfigHandler.GLOBAL_STAFF_CRAFTING_EXP,
				new Item[] {ItemInit.STAFF_IRON, ItemInit.STAFF_KOBOLD, ItemInit.STAFF_COPPER, ItemInit.STAFF_SILVER, ItemInit.STAFF_BRONZE, ItemInit.STAFF_PLATINUM,
				ItemInit.STAFF_STEEL, ItemInit.STAFF_SHADOW_PLATINUM, ItemInit.STAFF_FROST_STEEL, ItemInit.STAFF_OBSIDIAN, ItemInit.STAFF_CRYSTALLITE, ItemInit.STAFF_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.LONGSWORD_HOT_TOOL_HEAD_2, ItemInit.HOT_TOOL_ROD_2, "longsword", ConfigHandler.GLOBAL_LONGSWORD_CRAFTING_EXP,
				new Item[] {ItemInit.LONGSWORD_IRON, ItemInit.LONGSWORD_KOBOLD, ItemInit.LONGSWORD_COPPER, ItemInit.LONGSWORD_SILVER, ItemInit.LONGSWORD_BRONZE, ItemInit.LONGSWORD_PLATINUM,
				ItemInit.LONGSWORD_STEEL, ItemInit.LONGSWORD_SHADOW_PLATINUM, ItemInit.LONGSWORD_FROST_STEEL, ItemInit.LONGSWORD_OBSIDIAN, ItemInit.LONGSWORD_CRYSTALLITE, ItemInit.LONGSWORD_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.BATTLEAXE_HOT_TOOL_HEAD_2, ItemInit.LONG_TOOL_ROD, "battleaxe", ConfigHandler.GLOBAL_BATTLEAXE_CRAFTING_EXP,
				new Item[] {ItemInit.BATTLEAXE_IRON, ItemInit.BATTLEAXE_KOBOLD, ItemInit.BATTLEAXE_COPPER, ItemInit.BATTLEAXE_SILVER, ItemInit.BATTLEAXE_BRONZE, ItemInit.BATTLEAXE_PLATINUM,
				ItemInit.BATTLEAXE_STEEL, ItemInit.BATTLEAXE_SHADOW_PLATINUM, ItemInit.BATTLEAXE_FROST_STEEL, ItemInit.BATTLEAXE_OBSIDIAN, ItemInit.BATTLEAXE_CRYSTALLITE, ItemInit.BATTLEAXE_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.ZWEIHANDER_HOT_TOOL_HEAD_2, ItemInit.HOT_TOOL_ROD_2, "zweihander", ConfigHandler.GLOBAL_ZWEIHANDER_CRAFTING_EXP,
				new Item[] {ItemInit.ZWEIHANDER_IRON, ItemInit.ZWEIHANDER_KOBOLD, ItemInit.ZWEIHANDER_COPPER, ItemInit.ZWEIHANDER_SILVER, ItemInit.ZWEIHANDER_BRONZE, ItemInit.ZWEIHANDER_PLATINUM,
				ItemInit.ZWEIHANDER_STEEL, ItemInit.ZWEIHANDER_SHADOW_PLATINUM, ItemInit.ZWEIHANDER_FROST_STEEL, ItemInit.ZWEIHANDER_OBSIDIAN, ItemInit.ZWEIHANDER_CRYSTALLITE, ItemInit.ZWEIHANDER_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.KODACHI_HOT_TOOL_HEAD_2, ItemInit.HOT_TOOL_ROD_2, "kodachi", ConfigHandler.GLOBAL_KODACHI_CRAFTING_EXP,
				new Item[] {ItemInit.KODACHI_IRON, ItemInit.KODACHI_KOBOLD, ItemInit.KODACHI_COPPER, ItemInit.KODACHI_SILVER, ItemInit.KODACHI_BRONZE, ItemInit.KODACHI_PLATINUM,
				ItemInit.KODACHI_STEEL, ItemInit.KODACHI_SHADOW_PLATINUM, ItemInit.KODACHI_FROST_STEEL, ItemInit.KODACHI_OBSIDIAN, ItemInit.KODACHI_CRYSTALLITE, ItemInit.KODACHI_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.NODACHI_HOT_TOOL_HEAD_2, ItemInit.HOT_TOOL_ROD_2, "nodachi", ConfigHandler.GLOBAL_NODACHI_CRAFTING_EXP,
				new Item[] {ItemInit.NODACHI_IRON, ItemInit.NODACHI_KOBOLD, ItemInit.NODACHI_COPPER, ItemInit.NODACHI_SILVER, ItemInit.NODACHI_BRONZE, ItemInit.NODACHI_PLATINUM,
				ItemInit.NODACHI_STEEL, ItemInit.NODACHI_SHADOW_PLATINUM, ItemInit.NODACHI_FROST_STEEL, ItemInit.NODACHI_OBSIDIAN, ItemInit.NODACHI_CRYSTALLITE, ItemInit.NODACHI_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.SABRE_HOT_TOOL_HEAD_2, ItemInit.HOT_TOOL_ROD_2, "sabre", ConfigHandler.GLOBAL_SABRE_CRAFTING_EXP,
				new Item[] {ItemInit.SABRE_IRON, ItemInit.SABRE_KOBOLD, ItemInit.SABRE_COPPER, ItemInit.SABRE_SILVER, ItemInit.SABRE_BRONZE, ItemInit.SABRE_PLATINUM,
				ItemInit.SABRE_STEEL, ItemInit.SABRE_SHADOW_PLATINUM, ItemInit.SABRE_FROST_STEEL, ItemInit.SABRE_OBSIDIAN, ItemInit.SABRE_CRYSTALLITE, ItemInit.SABRE_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.MAKHAIRA_HOT_TOOL_HEAD_2, ItemInit.HOT_TOOL_ROD_2, "makhaira", ConfigHandler.GLOBAL_MAKHAIRA_CRAFTING_EXP,
				new Item[] {ItemInit.MAKHAIRA_IRON, ItemInit.MAKHAIRA_KOBOLD, ItemInit.MAKHAIRA_COPPER, ItemInit.MAKHAIRA_SILVER, ItemInit.MAKHAIRA_BRONZE, ItemInit.MAKHAIRA_PLATINUM,
				ItemInit.MAKHAIRA_STEEL, ItemInit.MAKHAIRA_SHADOW_PLATINUM, ItemInit.MAKHAIRA_FROST_STEEL, ItemInit.MAKHAIRA_OBSIDIAN, ItemInit.MAKHAIRA_CRYSTALLITE, ItemInit.MAKHAIRA_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.SPEAR_HOT_TOOL_HEAD_2, ItemInit.LONG_TOOL_ROD, "spear", ConfigHandler.GLOBAL_SPEAR_CRAFTING_EXP,
				new Item[] {ItemInit.SPEAR_IRON, ItemInit.SPEAR_KOBOLD, ItemInit.SPEAR_COPPER, ItemInit.SPEAR_SILVER, ItemInit.SPEAR_BRONZE, ItemInit.SPEAR_PLATINUM,
				ItemInit.SPEAR_STEEL, ItemInit.SPEAR_SHADOW_PLATINUM, ItemInit.SPEAR_FROST_STEEL, ItemInit.SPEAR_OBSIDIAN, ItemInit.SPEAR_CRYSTALLITE, ItemInit.SPEAR_DUSKSTEEL});
		
		registerNewRecipe(ItemInit.HOT_TOOL_ROD_2, ItemInit.HOT_TOOL_ROD_2, "handle", ConfigHandler.GLOBAL_LONG_WEAPON_HANDLE_CRAFTING_EXP,
				new Item[] {ItemInit.LONG_TOOL_ROD, ItemInit.LONG_TOOL_ROD, ItemInit.LONG_TOOL_ROD, ItemInit.LONG_TOOL_ROD, ItemInit.LONG_TOOL_ROD, ItemInit.LONG_TOOL_ROD,
				ItemInit.LONG_TOOL_ROD, ItemInit.LONG_TOOL_ROD, ItemInit.LONG_TOOL_ROD, ItemInit.LONG_TOOL_ROD, ItemInit.LONG_TOOL_ROD, ItemInit.LONG_TOOL_ROD});
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.ARMOR_PLATE_STEEL}, new Item[] {Items.DIAMOND}, "armor", 
				ConfigHandler.GLOBAL_ARMOR_PLATE_CRAFTING_EXP, ItemInit.ARMOR_PLATE_DIAMOND);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_IRON}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_IRON);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_IRON}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_IRON);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_IRON}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_IRON);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_IRON}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_IRON);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_GOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_GOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_GOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_GOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_GOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_GOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_GOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_GOLD);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_DIAMOND}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.STUDDED_HELMET_DIAMOND);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_DIAMOND}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.STUDDED_CHESTPLATE_DIAMOND);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_DIAMOND}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.STUDDED_LEGGINGS_DIAMOND);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_DIAMOND}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.STUDDED_BOOTS_DIAMOND);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_KOBOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_KOBOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_KOBOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_KOBOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_KOBOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_KOBOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_KOBOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_KOBOLD);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_COPPER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_COPPER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_COPPER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_COPPER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_COPPER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_COPPER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_COPPER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_COPPER);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_SILVER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_SILVER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_SILVER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_SILVER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_SILVER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_SILVER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_SILVER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_SILVER);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_BRONZE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_BRONZE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_BRONZE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_BRONZE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_BRONZE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_BRONZE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_BRONZE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_BRONZE);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_PLATINUM);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_STEEL);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_SHADOW_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_SHADOW_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_SHADOW_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_SHADOW_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_SHADOW_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_SHADOW_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_SHADOW_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_SHADOW_PLATINUM);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_FROST_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_FROST_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_FROST_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_FROST_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_FROST_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_FROST_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_FROST_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_FROST_STEEL);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_OBSIDIAN}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_OBSIDIAN);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_OBSIDIAN}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_OBSIDIAN);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_OBSIDIAN}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_OBSIDIAN);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_OBSIDIAN}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_OBSIDIAN);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_CRYSTALLITE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_CRYSTALLITE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_CRYSTALLITE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_CRYSTALLITE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_CRYSTALLITE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_CRYSTALLITE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_CRYSTALLITE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_CRYSTALLITE);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_HELMET_DUSKSTEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_HELMET_DUSKSTEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_CHESTPLATE_DUSKSTEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_CHESTPLATE_DUSKSTEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_LEGGINGS_DUSKSTEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_LEGGINGS_DUSKSTEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_CHAIN_BOOTS_DUSKSTEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHAIN_BOOTS_DUSKSTEEL);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_IRON}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_IRON);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_IRON}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_IRON);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_IRON}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_IRON);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_IRON}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_IRON);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_GOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_GOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_GOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_GOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_GOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_GOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_GOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_GOLD);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_DIAMOND}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.HELMET_DIAMOND);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_DIAMOND}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.CHESTPLATE_DIAMOND);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_DIAMOND}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.LEGGINGS_DIAMOND);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_DIAMOND}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.BOOTS_DIAMOND);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_KOBOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_KOBOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_KOBOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_KOBOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_KOBOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_KOBOLD);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_KOBOLD}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_KOBOLD);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_COPPER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_COPPER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_COPPER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_COPPER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_COPPER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_COPPER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_COPPER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_COPPER);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_SILVER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_SILVER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_SILVER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_SILVER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_SILVER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_SILVER);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_SILVER}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_SILVER);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_BRONZE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_BRONZE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_BRONZE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_BRONZE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_BRONZE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_BRONZE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_BRONZE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_BRONZE);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_PLATINUM);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_STEEL);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_SHADOW_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_SHADOW_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_SHADOW_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_SHADOW_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_SHADOW_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_SHADOW_PLATINUM);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_SHADOW_PLATINUM}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_SHADOW_PLATINUM);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_FROST_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_FROST_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_FROST_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_FROST_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_FROST_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_FROST_STEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_FROST_STEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_FROST_STEEL);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_OBSIDIAN}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_OBSIDIAN);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_OBSIDIAN}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_OBSIDIAN);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_OBSIDIAN}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_OBSIDIAN);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_OBSIDIAN}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_OBSIDIAN);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_CRYSTALLITE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_CRYSTALLITE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_CRYSTALLITE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_CRYSTALLITE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_CRYSTALLITE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_CRYSTALLITE);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_CRYSTALLITE}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_CRYSTALLITE);
		
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_HELMET_DUSKSTEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_HELMET_DUSKSTEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_CHESTPLATE_DUSKSTEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_CHESTPLATE_DUSKSTEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_LEGGINGS_DUSKSTEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_LEGGINGS_DUSKSTEEL);
		registerNewRecipeListedInputs(new Item[] {ItemInit.UNBOUND_PLATE_BOOTS_DUSKSTEEL}, new Item[] {ItemInit.LEATHER_BINDING, ItemInit.CHAIN_BINDING_IRON, 
				ItemInit.CHAIN_BINDING_KOBOLD, ItemInit.CHAIN_BINDING_GOLD, ItemInit.CHAIN_BINDING_COPPER, ItemInit.CHAIN_BINDING_SILVER, 
				ItemInit.CHAIN_BINDING_BRONZE, ItemInit.CHAIN_BINDING_PLATINUM, ItemInit.CHAIN_BINDING_STEEL, ItemInit.CHAIN_BINDING_SHADOW_PLATINUM,
				ItemInit.CHAIN_BINDING_FROST_STEEL, ItemInit.CHAIN_BINDING_OBSIDIAN, ItemInit.CHAIN_BINDING_CRYSTALLITE, ItemInit.CHAIN_BINDING_DUSKSTEEL},
				"armor", 0, ItemInit.PLATE_BOOTS_DUSKSTEEL);
		registerJeiHotToolHeadRecipes();
	}
	
	private void registerJeiHotToolHeadRecipes() {
		toolHeadJeiMap.add(new ItemStack(ItemInit.HOT_TOOL_HEAD));
		jeiRecipes.put(new ItemStack(Items.IRON_INGOT), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_KOBOLD), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_COPPER), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_SILVER), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_BRONZE), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_PLATINUM), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_STEEL), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_SHADOW_PLATINUM), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_FROST_STEEL), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_OBSIDIAN), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_CRYSTALLITE), ItemStack.EMPTY, toolHeadJeiMap);
		jeiRecipes.put(new ItemStack(ItemInit.INGOT_DUSKSTEEL), ItemStack.EMPTY, toolHeadJeiMap);
	}
	
	public ItemStack getItemResult(String material, Item input1, Item input2) {
		if(input1 == ItemInit.HOT_TOOL_ROD_2 && input2 == ItemInit.HOT_TOOL_ROD_2) {
			return new ItemStack(ItemInit.LONG_TOOL_ROD);
		}
		
		final HashMap<String, Item> recipe = recipes.get(input1, input2);
		if(recipe != null) {
			return new ItemStack(recipe.get(material));
		}
		
		return ItemStack.EMPTY;
	}
	
	public ItemStack getArmorBindingResult(Item input1, Item input2) {		
		ItemStack result = ItemStack.EMPTY;
		Set<Cell<List<Item>, List<Item>, Item>> cellSet = armorRecipes.cellSet();
		for(Cell<List<Item>, List<Item>, Item> c : cellSet) {
			if(c.getRowKey().contains(input1) && c.getColumnKey().contains(input2)) {
				result = new ItemStack(armorRecipes.get(c.getRowKey(), c.getColumnKey()));
				break;
			}
		}
		
		return result;
	}
	
	public int getExpValue(ItemStack stack) {
		Map<Item, Integer> exp = getExpValues();
		for(Item compStack : exp.keySet()) {
			if(compStack == stack.getItem()) {
				return exp.get(compStack);
			}
		}
		return 0;
	}
	
	public Map<Item, Integer> getExpValues(){
		return INSTANCE.expValues;
	}
	
	public Table<Item, Item, HashMap<String, Item>> getDualCraftingList(){
		return INSTANCE.recipes;
	}
	
	public Table<ItemStack, ItemStack, List<ItemStack>> getJeiCraftingList(){
		return INSTANCE.jeiRecipes;
	}
	
	public Table<List<Item>, List<Item>, Item> getArmorCraftingList() {
		return INSTANCE.armorRecipes;
	}
	
	public Table<List<Item>, List<Item>, Item> registerNewRecipeListedInputs(Item[] input1, Item[] input2, String type, int exp, Item output) {
		armorRecipes.put(Arrays.asList(input1), Arrays.asList(input2), output);
		return armorRecipes;
	}
	
	public Table<Item, Item, HashMap<String, Item>> registerNewRecipe(Item input1, Item input2, String type, int exp, String[] mats, Item[] items){
		if(!(recipes.contains(input1, input2))) {
			coverMaterials(input1, input2, type, exp, mats, items);
		}
		return recipes;
	}
	
	public Table<Item, Item, HashMap<String, Item>> registerNewRecipe(Item input1, Item input2, String type, int exp, Item[] items){
		if(!(recipes.contains(input1, input2))) {
			coverMaterials(input1, input2, type, exp, null, items);
		}
		return recipes;
	}
	
	private void coverMaterials(Item input1, Item input2, String type, int exp, @Nullable String[] mats, Item[] items) {
		HashMap<String, Item> matMap = new HashMap<String, Item>();
		List<ItemStack> jeiMap = new ArrayList<ItemStack>(13);
		String[] defaultMats = {"Iron", "Kobold", "Copper", "Silver", "Bronze", "Platinum", "Steel", "Shadow Platinum", "Frost Steel", "Obsidian", "Crystallite", "Dusksteel"};
		if(mats == null && items.length == defaultMats.length) {
			
			for(int i = 0; i < items.length; i++) {
				matMap.put(defaultMats[i], items[i]);
			}
		}else if(mats != null) {
			
			for(int i = 0; i < mats.length; i++) {
				matMap.put(mats[i], items[i]);
			}
		}
		recipes.put(input1, input2, matMap);
		for(Item stack : matMap.values()) {
			jeiMap.add(new ItemStack(stack));
		}
		jeiRecipes.put(new ItemStack(input1), new ItemStack(input2), jeiMap);
		
		for(int i = 0; i < items.length; i++) {
			expValues.put(items[i], exp + i);
		}
	}
}
